# Generated by Django 5.2.4 on 2025-07-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='fasting_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtest',
            name='reference_values',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='sample_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='labtest',
            name='technician',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='allergies_noted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vital_signs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmacy_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='refills_allowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='refills_used',
            field=models.IntegerField(default=0),
        ),
    ]
