# Generated by Django 5.2.4 on 2025-07-27 13:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=100)),
                ('purpose', models.TextField(blank=True)),
                ('idType', models.CharField(blank=True, max_length=50)),
                ('idNumber', models.CharField(blank=True, max_length=100)),
                ('checkInTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('visiting', 'Visiting'), ('waiting', 'Waiting'), ('checked-out', 'Checked Out')], default='visiting', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
