# Generated by Django 5.2.4 on 2025-07-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0002_bed_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bed',
            options={'ordering': ['ward', 'number']},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'ordering': ['name']},
        ),
    ]
